/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as EntityRouteImport } from './routes/entity'
import { Route as IndexRouteImport } from './routes/index'

const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityRoute = EntityRouteImport.update({
  id: '/entity',
  path: '/entity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entity': typeof EntityRoute
  '/masters': typeof MastersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entity': typeof EntityRoute
  '/masters': typeof MastersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entity': typeof EntityRoute
  '/masters': typeof MastersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/entity' | '/masters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entity' | '/masters'
  id: '__root__' | '/' | '/entity' | '/masters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntityRoute: typeof EntityRoute
  MastersRoute: typeof MastersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity': {
      id: '/entity'
      path: '/entity'
      fullPath: '/entity'
      preLoaderRoute: typeof EntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntityRoute: EntityRoute,
  MastersRoute: MastersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
